name: Test

on: 
  push:
    branches:
      - testing

jobs:

  test:
    strategy:
      matrix:
        go-version: [1.13x, 1.14x, 1.15x, 1.16x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install go
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.platform }}

    - uses: actions/checkout@v2

    - name: Test
      run: go test -v ./...
