name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: list1
      run: ls
    - name: list2
      run: ls ./test_go
    - name: list3
      run: ./../../test_go/
    - name: Build
      run: go build -v ./../../test_go/

    - name: Test
      run: go test -v ./../../test_go/
