name: "🚀 publish"

on:
    push:
      branches: [ main ]

jobs:
    release:
        name: 🚀 publish
        runs-on: ubuntu-latest
        if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
        strategy: 
          matrix:
            node-version: [15.x]
        steps:
        - uses: actions/checkout@v2
        - name: 🟢 Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
            token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        - name: 🚀 bump and push
          - run: git config --global user.name 'Danny-Dasilva'
          - run: git config --global user.email 'secrets.EMAIL'
          - run: npm version patch -m "[RELEASE] %s"
          - run: git push
          
       
        - name: 🚀 publish
          run: npm publish --access public
          working-directory: ./my-package
          env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}